#!/bin/bash

# set up
mkfifo /tmp/dunnet_{in,out}putFifo
cat > /tmp/dunnet_inputFifo &

# ask for game
echo "What game?"
read game

# setting up the game
cat /tmp/dunnet_inputFifo | $game > /tmp/dunnet_outputFifo &

# starting and connecting with annali
cat /tmp/dunnet_outputFifo | node dunnetAnnaLi.js > /tmp/dunnet_inputFifo &

#that is all.
